name: Serialize PMB to PFP-CIDOC

on:
  workflow_dispatch:

jobs:
  download:
    name: serialize PMB to PFP-CIDOC
    runs-on: ubuntu-latest
    env:
      OWNCLOUD_USER: ${{ secrets.OWNCLOUD_USER }}
      OWNCLOUD_PW: ${{ secrets.OWNCLOUD_PW }}
      NO_LIMIT: 1
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v4
      - name: Install Python Packages
        run: |
          pip install -r requirements.txt
      - name: dump the data
        run: ./scripts/build_graph.sh
      - name: validate the data
        run: ./scripts/validate.sh
      - name: Upload validation report
        uses: actions/upload-artifact@v3
        with:
          name: validation-report
          path: datasets/validation_report.txt